runtime: nodejs18
env: standard

automatic_scaling:
  min_instances: 1
  max_instances: 1

network:
  session_affinity: true

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  NUXT_PUBLIC_PUBLIC_URL: 'https://storage.googleapis.com/academyc284bsy3897-dikoding'
